### ISSUE TITLE
Jacobian

### ISSUE THREAD

**Issue by Plancalkuele** [pbrod/numdifftools#22] opened 2016-06-24 15:17 UTC
I'm trying to generate the Jacobian from a function in which i use math.fsum()  for making the function adaptable to the number of input values given.

Here is the code:

```
import math
import numpy as np
import numdifftools as nd

Const = 1.64735
N = np.array([2, 4, 2])
M = np.array([1])
E = np.array([1])
C = np.array([0.9218, 0.5780, 2.1182])
D = np.array([0.2610])
O = np.array([0.7410])

y_pred = lambda C,D,O: Const + math.fsum(N*C) + math.fsum(M*D) + math.fsum(E*O)

jac = nd.Jacobian(y_pred)(C,D,O)

print(jac)
```
The output is:
`[[ 2.  4.  2.]]`

Which is basically the array N and not what I want to generate, the Jacobian.
Is it possible to define a function like this (with a sum function) and then try to generate the Jacobian?

**Comment by pbrod** [comment] 2016-06-24 17:26
All methods in numdifftools differentiate the function f(x, *args, **kwds) with respect to x. Thus 
in order to get correct result in your case, you must rewrite your function with array input. 
One rewrite could be like this:

>>> y_pred = lambda x: Const + math.fsum(N*x[:3]) + math.fsum(M*x[3]) + math.fsum(E*x[4:])
>>> nd.Jacobian(y_pred)(np.hstack((C,D,O)))
 array([[ 2.,  4.,  2.,  1.,  1.]])

Closing this issue since it is not a bug.

**Closed by pbrod** 2016-06-24 17:26 UTC

**Comment by Plancalkuele** [comment] 2016-06-24 17:49
Thank you very much! You could mark this issue as a question...
This would also be very useful as an example for the documentation. Thanks again.
